instance_groups:
- azs:
  - z1
  - z2
  - z3
  instances: 3
  jobs:
  - name: vault
    release: safe
  name: vault
  networks:
  - name: vault
    static_ips:
    - 10.213.13.7
    - 10.213.13.8
    - 10.213.13.9
  persistent_disk_pool: vault
  properties:
    safe:
      cluster_ips:
      - 10.213.13.7
      - 10.213.13.8
      - 10.213.13.9
      peer:
        tls:
          ca: REDACTED
          certificate: REDACTED
          key: REDACTED
  stemcell: default
  vm_type: small
name: drgao-proto-vault
releases:
- name: safe
  sha1: a83139d3b4ae64736f89cc921d46ce4c50d685e7
  url: https://github.com/cloudfoundry-community/safe-boshrelease/releases/download/v0.0.6/safe-0.0.6.tgz
  version: 0.0.6
stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest
update:
  canaries: 1
  canary_watch_time: 30000-120000
  max_in_flight: 1
  serial: true
  update_watch_time: 30000-120000

